export { default as Navbar } from './Navbar/Navbar'
export { default as Hero } from './Hero/Hero'
export { default as Projects } from './Projects/Projects'
export { default as Technologies } from './Technologies/Technologies'
export { default as About } from './About/About'
export { default as Chrono } from './Chrono/Chrono'
export { default as Footer } from './Footer/Footer'
